### ISSUE TITLE
Feature request - HyperHDR as supported Hyperion.NG fork

### ISSUE THREAD

**Issue by pandel** [felixganzer/ioBroker.hyperion_ng#10]
Hi!

It would be nice, if HyperHDR (https://github.com/awawa-dev/HyperHDR), as Hyperion.NG fork, would be supported. I think, most of the common parameters should be similar and at least turning things on and off or setting effects should be possible. At the moment the adapter only tells me

Your Version of hyperion (16.0.0.1) is not supported!!

and I cannot find out, if there should be more datapoints than the general ones that the adapter created.

EDIT: I modified line https://github.com/felixganzer/ioBroker.hyperion_ng/blob/28d7585c3f5ae5ae0b34bff8c093c25165eaad85/main.js#L605 and commented it out. Your adapter seems to work perfectly though.

Regards
Holger

**Comment by felixganzer** [comment]
I added the version Checking for your HyperHDR. I have to use it, because hyperion 1.X has a different API.
