### ISSUE TITLE
Cant set states

### ISSUE THREAD

**Issue by develarts** [felixganzer/ioBroker.hyperion_ng#13]
Hello,
i cant change values. Hyperion dont react.
All installed correctly, seing all components/instances, when i changed whatever "ALL" components status to off, dont reaction. dont switched

**Comment by Beneli21** [comment]
I've encountered the same issue today. Here is my quick and dirty fix:

Open hyperion_API.js, go to function "setComponentStatus" (line 247). Change it to:

`async setComponentStatus(component, state, instance, callback) {`
`    component = component.replace(/_/g, "");`
`    adapterMain.log.info('set component ' + component + ' of instance ' + parseInt(instance) + ' to ' + state);`

**Comment by felixganzer** [comment]
Thanks, I will add this.
