### ISSUE TITLE
Warnung - State "hyperion_ng.0." has no existing object

### ISSUE THREAD

**Issue by OberfragGER** [felixganzer/ioBroker.hyperion_ng#15]
Hallo,

ich bekomme im Protokoll immer folgende Warnung:
`hyperion_ng.0 | 2021-12-23 10:15:18.987 | warn | State "hyperion_ng.0." has no existing object, this might lead to an error in future versions`

NodeJs - 14.18.2
Host - 3.3.22

**Comment by sucmerep** [comment]
nicht 100% sicher aber sieht eher aus wie wenn dein Script nicht funktionieren würde

**Comment by OberfragGER** [comment]
Ich denke wir schließen mal. Kam in der letzten Zeit irgendwie nicht mehr vor bzw. ist mir nicht aufgefallen...
