### ISSUE TITLE
Names of components has changed

### ISSUE THREAD

**Issue by Dennis1987m** [felixganzer/ioBroker.hyperion_ng#16]
It seems like the names of the components has changed. E.g. from "LEDDEVICES" to _LEDDEVICE_.

This leads to the following message in the log (see attachment). Also I can't change the states via blocky. Do I do something wrong or is it a bug
<img width="1301" alt="Bildschirmfoto 2022-01-08 um 18 47 30" src="https://user-images.githubusercontent.com/69116205/148654354-689e0217-6e3d-44fa-9b3a-46300948a8e0.png">
?

And this happens if I try to change the state of a component via blockly:
<img width="1157" alt="Bildschirmfoto 2022-01-08 um 18 57 21" src="https://user-images.githubusercontent.com/69116205/148654597-2d88dcbd-b51c-4426-8fe0-5960bef10043.png">

**Comment by felixganzer** [comment]
Fehler behoben
