### ISSUE TITLE
Clear All funktioniert nicht

### ISSUE THREAD

**Issue by Cosmicbase** [felixganzer/ioBroker.hyperion_ng#3]
Seit dem Update 0.1.18 (2021.03.06)
funktioniert Clear All nicht mehr. 
Bisher konnte ich über den Adapter "clear all" absetzen und Effekte, Farben etc. zurücksetzen.
Leider funktioniert ein downgrade auf 0.1.17 auch nicht. Weil die 0.1.17 nicht in der Repository ist. Ich möchte hier nochmal testen.

**Comment by felixganzer** [comment]
Ich schaue mir das heute abend mal an

**Comment by felixganzer** [comment]
Ich habe mal kurz bei mir getestet. Bei mir funktioniert alles. Ich habe an dieser Stelle auch nichts geändert. Ich musste mal ein paar State Namen ändern. Probiere mal alle Datenpunkte zu löschen und versuche es dann noch einmal.

**Comment by Cosmicbase** [comment]
Hat sich erledigt, der Clear All Fehler hat sich in Hyperion NG selber eingeschlichen.

Eine andere Frage hätte ich in Bezug Instanzen.
Kann ich einzelne Instanzen über den Adapter Ein/Aus schalten?
Ich meine nicht Komponenten sondern direkt Instanz.

**Comment by felixganzer** [comment]
Ja das geht. Du kannst in jeder Instanz den State running auf false setzen

**Comment by Cosmicbase** [comment]
Hi Felix, das hat geklappt mit den Instanzen auszuschalten.
Nur leider läuft scheinbar die USB Komponente im Hintergrund weiter weil sie zuvor nicht deaktiviert wurde.
Lässt sich die USB oder LED Device auch einzeln ausschalten?

**Comment by felixganzer** [comment]
Ja das geht alles. Alles was in der "Fernbedienung" auf dem Hyperion Webinterface funktioniert, funktioniert in dem Adapter auch. Das müsste über die Komponenten funktionieren.

**Comment by Cosmicbase** [comment]
Sehr schön, dann probiere ich das heute Abend aus. Ich möchte nähmlich gerne meine Instanzen getrennt voneinander steuern.

- First LED Hardware instance  - USB Hardware 
- Lampe - USB Hardware
- Bilderrahmen - USB Hardware

Wenn ich die USB-Aufnahme von der Lampe oder Bilderrahmen deaktiviere , soll trotzdem die USB-Aufnahme von der 
First LED Hardware instance weiterlaufen, bzw. muss ich alle USB-Aufnahmen stoppen, weil sonst der USB 3.0 Grabber weiterläuft und somit unnötig Ressourcen verbraucht.
