### ISSUE TITLE
Fehler bei Farben Hyperion NG 10

### ISSUE THREAD

**Issue by Cosmicbase** [felixganzer/ioBroker.hyperion_ng#9]
Die einzelnen Farben werden seit Hyperion NG 10 nicht mehr angezeigt.
Mit der Hyperion NG 9 konnte ich über die VIS Effekte sowie Farben wunderbar absetzen. 

- Effekte funktionieren noch nachwievor 
- Farben nicht mehr

Bitte schauen ob sich beim absetzen der Farben sowie bei den DP was geändert hat.

Vielen Dank

**Comment by felixganzer** [comment]
Wir müssen warten, bis die Dokumentation geupdated wurde. Ich kann mir das in einer Woche mal anschauen.

**Comment by Cosmicbase** [comment]
Das sich was geändert hat ist denke ich offensichtlich. Bisher hat das absetzen von Farben und Helligkeit super funktioniert.
Kann natürlich sein das es auch umgewandelt gehört. 
Aber Node-Red sollte nicht die Lösung sein.
Sollte wie gewohnt auch über den Adapter funktionieren. 
Wenn logs oder ähnliches benötigt werden dann Info an mich.

**Comment by felixganzer** [comment]
Ich habe den Fehler behoben. Bei hyperion hat sich nichts geändert. Es ist nur weniger Fehlertoleranter geworden. Wenn ich einen Effekt oder eine Farbe mit der Duration 0 gesendet habe, habe ich aus Versehen eine Zeit von 0 mitgeschickt. in der Alpha 9 hat er das akzeptiert, in der Alpha 10 nicht. Der Fehler war bei den Effekten und  bei den Farben.

**Comment by Cosmicbase** [comment]
Danke 👍 passt wieder perfekt.
